require 'daru'

require_relative 'nyaplot/version'
require_relative 'nyaplot/base'
require_relative 'nyaplot/core'
require_relative 'nyaplot/diagram'
require_relative 'nyaplot/plot'
require_relative 'nyaplot/frame'
require_relative 'nyaplot/database'
require_relative 'nyaplot/color'
